Repository jmurphyau/ember-truth-helpers, pull requests merged in 2023-09, with the labels that each got.

#188 Fix Glint types by converting helpers to plain functions
  packages/ember-truth-helpers/package.json
  packages/ember-truth-helpers/src/helpers/and.ts
  packages/ember-truth-helpers/src/helpers/eq.ts
  packages/ember-truth-helpers/src/helpers/gt.ts
  packages/ember-truth-helpers/src/helpers/gte.ts
  packages/ember-truth-helpers/src/helpers/is-array.ts
  packages/ember-truth-helpers/src/helpers/is-empty.ts
  packages/ember-truth-helpers/src/helpers/is-equal.ts
  packages/ember-truth-helpers/src/helpers/lt.ts
  packages/ember-truth-helpers/src/helpers/lte.ts
  packages/ember-truth-helpers/src/helpers/not-eq.ts
  packages/ember-truth-helpers/src/helpers/not.ts
  packages/ember-truth-helpers/src/helpers/or.ts
  packages/ember-truth-helpers/src/helpers/xor.ts
  packages/modern-test-app/app/components/and-or-type-checking.hbs
  packages/modern-test-app/app/components/and-or-type-checking.ts
  packages/modern-test-app/app/templates/helpers.hbs
  packages/test-app/tests/unit/helpers/and-test.js
  packages/test-app/tests/unit/helpers/or-test.js
  pnpm-lock.yaml
Labels: bug

#192 Update Ember.js compatibiity in README.md
  README.md
Labels: documentation

#195 Fix peerDependencies to depend on ember-source@>=3.28.0
  packages/ember-truth-helpers/package.json
Labels: bug

#197 Use the workspace protocol to be super extra sure that we're using the
  package.json
  packages/modern-test-app/package.json
  packages/test-app/package.json
  pnpm-lock.yaml
Labels: internal

#196 Improve types for `and` and `or`
  packages/ember-truth-helpers/package.json
  packages/ember-truth-helpers/src/helpers/and.ts
  packages/ember-truth-helpers/src/helpers/not.ts
  packages/ember-truth-helpers/src/helpers/or.ts
  packages/ember-truth-helpers/src/utils/truth-convert.ts
  packages/ember-truth-helpers/type-tests/helpers/and.test.ts
  packages/ember-truth-helpers/type-tests/helpers/or.test.ts
  packages/ember-truth-helpers/type-tests/tsconfig.json
  packages/ember-truth-helpers/type-tests/utils/truth-convert.test.ts
  packages/modern-test-app/app/components/and-or-type-checking.hbs
  packages/modern-test-app/app/components/and-or-type-checking.ts
  packages/modern-test-app/app/templates/helpers.hbs
  pnpm-lock.yaml
Labels: bug

#199 Fix types for `{{or}}` helper with fallback argument
  packages/ember-truth-helpers/src/helpers/or.ts
  packages/ember-truth-helpers/type-tests/helpers/or.test.ts
  packages/modern-test-app/app/components/and-or-type-checking.ts
  packages/modern-test-app/app/components/helpers.hbs
  packages/modern-test-app/app/components/helpers.ts
Labels: bug

#200 Further type improvements for `or` helper
  packages/ember-truth-helpers/src/helpers/or.ts
  packages/ember-truth-helpers/src/utils/truth-convert.ts
  packages/ember-truth-helpers/type-tests/helpers/or.test.ts
  packages/ember-truth-helpers/type-tests/utils/truth-convert.test.ts
Labels: bug

#201 Use put-built-npm-package-contents-on-branch@v2.0.0
  .github/workflows/push-dist.yml
Labels: internal
